name: Broken Links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
  pull_request:
  schedule:
    - cron: "00 00 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4.0.1
        with:
          title: Broken Link
          content-filepath: ./lychee/out.md
          labels: bug
