# Build the alpha branch, and deploy a snapshot to Central.
name: Alpha Snapshot Build

on:
  push:
    branches: [ alpha ] # Single branch called "alpha"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Alpha Snapshot on Java 8 (Zulu)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: maven
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      # Derive the project version to set in pom.xml
      - name: Derive Alpha Version Number
        run: echo "DERIVED_VERSION=alpha-SNAPSHOT" >> $GITHUB_ENV # Hard-coded, but consistent with build-beta.yml

      # Update the project version in pom.xml
      - name: Update Version
        run: mvn -B versions:set -DnewVersion=${{ env.DERIVED_VERSION }}

      - name: Build & Publish to Apache Maven Central
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: willhains
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
