# Update the version number in README.md
name: Update Version in README

on:
  push:
    branches: [ beta/* ] # Multiple beta branches for each version, e.g. "beta/1.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Get Version Numbers
        id: get-versions
        run: |
          echo "OLD_VERSION=$(git tag | tail -1 | sed 's_^v__')" >> $GITHUB_ENV
          echo "NEW_VERSION=$(git branch --show-current | sed 's_^beta/__')" >> $GITHUB_ENV

      - name: Update README
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          old-version: ${{ env.OLD_VERSION }}
          version: ${{ env.NEW_VERSION }}
          prefix: "<version>"
          suffix: "</version>"
          with-checkout: false

      - name: Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .
          message: "${{ env.NEW_VERSION }}: Update version in README."
